- name: deploy
  hosts: ctn
  vars:
    bit_user: 
    bit_pass: 
  tasks:
    - name: pull from git
      git:
        repo: https://{{bit_user|urlencode()}}:{{bit_pass|urlencode()}}@bitbucket.org/initiative-admin-backend/initiative-admin-backend.git
        dest: /root/iwater/initiative-admin-backend/
        update: yes
        version: master
    - name: deploy Docker Compose stack
      docker_compose:
        project_src: /root/iwater/
        files:
          - docker-compose.yml
        build: yes
        state: present
        debug: yes
        services:
            - django