# Generated by Django 4.0.6 on 2022-08-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0002_user_email_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_name', 'address', 'gst_no')},
        ),
    ]
