# Generated by Django 4.0.6 on 2022-08-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0003_alter_company_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='phone_verified',
            field=models.BooleanField(default=0, verbose_name='phone_verified'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
