# Generated by Django 4.0.6 on 2022-08-26 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0004_site_phone_verified_alter_site_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iwater.site'),
        ),
    ]
