# Generated by Django 4.0.6 on 2022-08-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0005_alter_device_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_company', to='iwater.company', verbose_name='site_company'),
        ),
    ]
