# Generated by Django 4.0.6 on 2022-08-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0006_site_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='otp_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
