# Generated by Django 4.0.6 on 2022-08-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0007_site_otp_site_otp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
