# Generated by Django 4.0.6 on 2022-09-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0009_sitecopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_company', to='iwater.company', verbose_name='subscription_company'),
        ),
    ]
