# Generated by Django 4.0.6 on 2022-09-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0010_subscription_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
