# Generated by Django 4.0.6 on 2022-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0011_alter_subscription_subscription_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expired',
            field=models.BooleanField(default=0, verbose_name='expired'),
        ),
    ]
