# Generated by Django 4.0.6 on 2022-09-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0014_alter_subscription_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_id', to='iwater.site', verbose_name='site_id'),
        ),
    ]
