# Generated by Django 4.0.6 on 2022-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0015_alter_subscription_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
