# Generated by Django 4.0.6 on 2022-09-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='phone'),
        ),
    ]
