# Generated by Django 4.0.6 on 2022-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0017_alter_user_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='company',
            name='address1',
            field=models.CharField(blank=True, max_length=200, verbose_name='address1'),
        ),
        migrations.AddField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=200, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='company',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, verbose_name='pincode'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=200, verbose_name='state'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_name', 'address1', 'gst_no')},
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
