# Generated by Django 4.0.6 on 2022-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0018_alter_company_unique_together_company_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
