# Generated by Django 4.0.6 on 2022-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0019_user_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_link_expired',
            field=models.BooleanField(default=False),
        ),
    ]
