# Generated by Django 4.0.6 on 2022-09-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0022_alter_site_unique_together_alter_site_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
    ]
