# Generated by Django 4.0.6 on 2022-10-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0024_site_token_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(default='Pending', max_length=254, verbose_name='payment_status')),
                ('provider_order_id', models.CharField(max_length=40, verbose_name='provider_order_id')),
                ('payment_id', models.CharField(max_length=36, verbose_name='payment_id')),
                ('signature_id', models.CharField(max_length=128, verbose_name='signature_id')),
                ('subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_id', to='iwater.subscription', verbose_name='subscription_id')),
            ],
        ),
    ]
