# Generated by Django 4.0.6 on 2022-10-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0025_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='iwater.subscription', verbose_name='subscription'),
        ),
    ]
