# Generated by Django 4.0.6 on 2022-10-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0027_remove_order_subscription_order_paid_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
