# Generated by Django 4.0.6 on 2022-10-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0029_subscription_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_name', 'pincode', 'gst_no')},
        ),
    ]
