# Generated by Django 4.0.6 on 2022-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0030_alter_company_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=0, verbose_name='phone_verified'),
        ),
    ]
