# Generated by Django 4.0.6 on 2022-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0031_user_otp_user_otp_created_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_accepted',
            field=models.BooleanField(default=0, verbose_name='invite_accepted'),
        ),
    ]
