# Generated by Django 4.0.6 on 2022-10-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0034_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='days_to_expire',
            field=models.SmallIntegerField(default=1),
        ),
    ]
