# Generated by Django 4.0.6 on 2022-10-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0035_alter_subscription_days_to_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_company', to='iwater.company', verbose_name='paid_company'),
        ),
    ]
