# Generated by Django 4.0.6 on 2022-10-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0036_order_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('phone_verified', models.BooleanField(default=0, verbose_name='phone_verified')),
                ('token_verified', models.BooleanField(default=0, verbose_name='token_verified')),
                ('status', models.BooleanField(default=True)),
                ('alerts', models.SmallIntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_treatment_unit', models.BooleanField(default=False, verbose_name='Is treatment')),
                ('is_dispensing_unit', models.BooleanField(default=False, verbose_name='Is dispensing')),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_site_company', to='iwater.company', verbose_name='site_company')),
            ],
            options={
                'db_table': 'iwater_archive_site',
                'unique_together': {('site_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ArchiveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name1', models.CharField(max_length=255, null=True, unique=True)),
                ('serial_no1', models.CharField(max_length=255, null=True, unique=True)),
                ('device_name2', models.CharField(max_length=255, null=True, unique=True)),
                ('serial_no2', models.CharField(max_length=255, null=True, unique=True)),
                ('device_name3', models.CharField(max_length=255, null=True, unique=True)),
                ('serial_no3', models.CharField(max_length=255, null=True, unique=True)),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='iwater.archivesite')),
            ],
        ),
    ]
