# Generated by Django 4.0.6 on 2022-10-27 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0037_archivesite_archivedevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSitePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_siteid', to='iwater.archivesite', verbose_name='siteid')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_site_user', to=settings.AUTH_USER_MODEL, verbose_name='userid')),
            ],
            options={
                'db_table': 'iwater_archive_site_permissions',
                'unique_together': {('user', 'site')},
            },
        ),
    ]
