# Generated by Django 4.0.6 on 2022-10-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0038_archivesitepermission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='archivedevice',
            table='iwater_archive_device',
        ),
    ]
