# Generated by Django 4.0.6 on 2022-11-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0041_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone'),
        ),
    ]
