# Generated by Django 4.0.6 on 2023-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0044_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
