# Generated by Django 4.2.2 on 2023-06-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0045_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device1_sub_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device2_sub_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device3_sub_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
