# Generated by Django 3.2.18 on 2023-08-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0046_device_device1_sub_status_device_device2_sub_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivesite',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
