# Generated by Django 3.2.18 on 2023-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0047_archivesite_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivesite',
            name='token',
        ),
        migrations.AddField(
            model_name='site',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
