# Generated by Django 3.2.18 on 2023-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwater', '0048_auto_20230804_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
